"""Reinitial migration with all correct models

Revision ID: 06dadff0ec9f
Revises: 
Create Date: 2025-08-02 09:30:59.833484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dadff0ec9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_signin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_provider_user_id'), type_='unique')
        batch_op.create_unique_constraint('uq_oauth_signin_provider_user_id', ['provider', 'provider_user_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('oauth_signin', schema=None) as batch_op:
        batch_op.drop_constraint('uq_oauth_signin_provider_user_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_provider_user_id'), ['provider', 'provider_user_id'])

    # ### end Alembic commands ###
