"""Migración inicial del sistema de rifas

Revision ID: 0c3ef37e9f40
Revises: f13e807a04f3
Create Date: 2025-09-09 10:41:26.041164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3ef37e9f40'
down_revision = 'f13e807a04f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('hora_inicio',
               existing_type=sa.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.alter_column('hora_inicio',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
