"""Agregado estado finalizar caminata

Revision ID: 2a4e8a4c4926
Revises: 
Create Date: 2025-08-05 00:36:49.301773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4e8a4c4926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caminata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneda', sa.String(length=10), server_default='CRC', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caminata', schema=None) as batch_op:
        batch_op.drop_column('moneda')

    # ### end Alembic commands ###
