"""Migración inicial del sistema de rifas

Revision ID: 3777e5d15b69
Revises: 0c3ef37e9f40
Create Date: 2025-09-09 11:01:52.605309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3777e5d15b69'
down_revision = '0c3ef37e9f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rifa_etiqueta')
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.drop_column('precio')

    op.create_table('rifa_etiqueta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rifa_id', sa.INTEGER(), nullable=False),
    sa.Column('etiqueta', sa.VARCHAR(length=255), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
