"""empty message

Revision ID: 386c7082876a
Revises: 4a95ce118da4
Create Date: 2025-09-01 13:42:32.520691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386c7082876a'
down_revision = '4a95ce118da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aerolinea')
    op.drop_table('transporte')
    op.drop_table('pre_alerta')
    op.drop_table('estadia')
    op.drop_table('lugar_visitar')
    op.drop_table('international_travel')
    op.drop_table('guia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), nullable=True),
    sa.Column('operador', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('precio_guia_pp', sa.FLOAT(), nullable=True),
    sa.Column('cpl', sa.VARCHAR(length=5), nullable=True),
    sa.Column('fecha_disponible', sa.DATE(), nullable=True),
    sa.Column('reserva', sa.VARCHAR(length=100), nullable=True),
    sa.Column('precio_acarreo', sa.FLOAT(), nullable=True),
    sa.Column('enlaces', sa.TEXT(), nullable=True),
    sa.Column('nota', sa.TEXT(), nullable=True),
    sa.Column('fecha_reserva', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international_travel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo_destino', sa.VARCHAR(length=200), nullable=False),
    sa.Column('flyer_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('nombre_viaje', sa.VARCHAR(length=200), nullable=False),
    sa.Column('precio_paquete', sa.FLOAT(), nullable=True),
    sa.Column('tipo_moneda', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tipo_cambio', sa.FLOAT(), nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('capacidad_con_guias', sa.INTEGER(), nullable=True),
    sa.Column('capacidad_sin_guias', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lugar_visitar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_lugar', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_sitio', sa.VARCHAR(length=200), nullable=True),
    sa.Column('precio_entrada', sa.FLOAT(), nullable=True),
    sa.Column('fecha_reserva', sa.DATE(), nullable=True),
    sa.Column('guia_local', sa.VARCHAR(length=5), nullable=True),
    sa.Column('nombre_guia', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono_lugar', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telefono_contacto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp_contacto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('enlaces', sa.TEXT(), nullable=True),
    sa.Column('nota', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contacto', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('precio_pp', sa.FLOAT(), nullable=True),
    sa.Column('cpl', sa.VARCHAR(length=5), nullable=True),
    sa.Column('fecha_disponible_reserva', sa.DATE(), nullable=True),
    sa.Column('alimentacion_incluida', sa.VARCHAR(length=5), nullable=True),
    sa.Column('cantidad_noches', sa.INTEGER(), nullable=True),
    sa.Column('enlaces', sa.TEXT(), nullable=True),
    sa.Column('nota', sa.TEXT(), nullable=True),
    sa.Column('fecha_entrada', sa.DATE(), nullable=True),
    sa.Column('fecha_salida', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_alerta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('banco', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono_entidad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_prealerta', sa.DATE(), nullable=True),
    sa.Column('nombre_asesor', sa.VARCHAR(length=150), nullable=True),
    sa.Column('hora_prealerta', sa.TIME(), nullable=True),
    sa.Column('numero_prealerta', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fecha_desde', sa.DATE(), nullable=True),
    sa.Column('fecha_hasta', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporte',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_transporte', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_transporte', sa.VARCHAR(length=200), nullable=True),
    sa.Column('conductor', sa.VARCHAR(length=150), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=True),
    sa.Column('fecha_contratacion', sa.DATE(), nullable=True),
    sa.Column('telefono_lugar', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telefono_contacto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp_contacto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('enlaces', sa.TEXT(), nullable=True),
    sa.Column('nota', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aerolinea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('travel_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_transporte', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nombre_aerolinea', sa.VARCHAR(length=150), nullable=True),
    sa.Column('telefono_aerolinea', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_prealertar', sa.DATE(), nullable=True),
    sa.Column('enlace_prealertar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('numero_vuelo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('horario_salida', sa.TIME(), nullable=True),
    sa.Column('horario_llegada', sa.TIME(), nullable=True),
    sa.Column('nombre_aeropuerto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('telefono_aeropuerto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('precio_asientos', sa.FLOAT(), nullable=True),
    sa.Column('precio_maletas_doc', sa.FLOAT(), nullable=True),
    sa.Column('equipaje_mano', sa.FLOAT(), nullable=True),
    sa.Column('precio_estandar', sa.FLOAT(), nullable=True),
    sa.Column('precio_mas_equipo', sa.FLOAT(), nullable=True),
    sa.Column('precio_salida_rapida', sa.FLOAT(), nullable=True),
    sa.Column('precio_premium', sa.FLOAT(), nullable=True),
    sa.Column('precio_vip', sa.FLOAT(), nullable=True),
    sa.Column('precio_basic', sa.FLOAT(), nullable=True),
    sa.Column('precio_classic', sa.FLOAT(), nullable=True),
    sa.Column('precio_flexible', sa.FLOAT(), nullable=True),
    sa.Column('precio_impuestos', sa.FLOAT(), nullable=True),
    sa.Column('otros_costos_json', sa.TEXT(), nullable=True),
    sa.Column('fecha_compra', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['travel_id'], ['international_travel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
