"""Datos para asegurado

Revision ID: 4031e8fdbc91
Revises: 8d16008a9e0f
Create Date: 2025-08-07 21:17:07.572368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4031e8fdbc91'
down_revision = '8d16008a9e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abono_caminata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_abono_crc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monto_abono_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tipo_cambio_bcr', sa.Float(), nullable=True))
        batch_op.drop_column('monto_abono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abono_caminata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_abono', sa.FLOAT(), nullable=False))
        batch_op.drop_column('tipo_cambio_bcr')
        batch_op.drop_column('monto_abono_usd')
        batch_op.drop_column('monto_abono_crc')

    # ### end Alembic commands ###
