"""empty message

Revision ID: 4a95ce118da4
Revises: 
Create Date: 2025-08-16 10:52:55.481186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a95ce118da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paquete_unico')
    op.drop_table('transporte_multiple')
    op.drop_table('intern')
    op.drop_table('otro_pago_multiple')
    op.drop_table('entrada_multiple')
    with op.batch_alter_table('international_travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad_con_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad_sin_guias', sa.Integer(), nullable=True))
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), nullable=True))
        batch_op.drop_column('capacidad_sin_guias')
        batch_op.drop_column('capacidad_con_guias')

    op.create_table('entrada_multiple',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('intern_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_lugar', sa.VARCHAR(length=150), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=True),
    sa.Column('incluye_poliza', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('hora', sa.TIME(), nullable=True),
    sa.Column('nombre_guia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono_lugar', sa.VARCHAR(length=20), nullable=True),
    sa.Column('telefono_guia', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otro_pago_multiple',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('intern_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intern',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo_destino', sa.VARCHAR(length=255), nullable=False),
    sa.Column('flyer_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nombre_viaje', sa.VARCHAR(length=255), nullable=False),
    sa.Column('precio_viaje', sa.FLOAT(), nullable=True),
    sa.Column('capacidad_sg', sa.INTEGER(), nullable=True),
    sa.Column('capacidad_cg', sa.INTEGER(), nullable=True),
    sa.Column('cantidad_dias', sa.INTEGER(), nullable=True),
    sa.Column('tipo_moneda', sa.VARCHAR(length=10), nullable=True),
    sa.Column('tipo_cambio', sa.FLOAT(), nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), nullable=False),
    sa.Column('un_solo_proveedor', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporte_multiple',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('intern_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_transporte', sa.VARCHAR(length=150), nullable=True),
    sa.Column('placa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nombre_conductor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono_conductor', sa.VARCHAR(length=20), nullable=True),
    sa.Column('telefono_empresa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('poliza', sa.BOOLEAN(), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquete_unico',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('intern_id', sa.INTEGER(), nullable=False),
    sa.Column('paquete_incluye', sa.TEXT(), nullable=True),
    sa.Column('nombre_empresa_operador', sa.VARCHAR(length=150), nullable=True),
    sa.Column('nombre_guia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono_empresa_operador', sa.VARCHAR(length=20), nullable=True),
    sa.Column('telefono_guia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('enlace_facebook', sa.VARCHAR(length=200), nullable=True),
    sa.Column('enlace_web', sa.VARCHAR(length=200), nullable=True),
    sa.Column('placa_transporte', sa.VARCHAR(length=20), nullable=True),
    sa.Column('telefono_conductor', sa.VARCHAR(length=20), nullable=True),
    sa.Column('incluye_otro_transporte', sa.BOOLEAN(), nullable=True),
    sa.Column('transporte_acuatico', sa.BOOLEAN(), nullable=True),
    sa.Column('transporte_aereo', sa.BOOLEAN(), nullable=True),
    sa.Column('transporte_auto', sa.BOOLEAN(), nullable=True),
    sa.Column('transporte_bus', sa.BOOLEAN(), nullable=True),
    sa.Column('transporte_buseta', sa.BOOLEAN(), nullable=True),
    sa.Column('poliza', sa.BOOLEAN(), nullable=True),
    sa.Column('alimentacion_incluida', sa.BOOLEAN(), nullable=True),
    sa.Column('descripcion_otros_servicios', sa.TEXT(), nullable=True),
    sa.Column('incluye_costos_adicionales', sa.BOOLEAN(), nullable=True),
    sa.Column('detalle_costo_adicional', sa.VARCHAR(length=200), nullable=True),
    sa.Column('precio_costo_adicional', sa.FLOAT(), nullable=True),
    sa.Column('forma_pago_costo_adicional', sa.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion_forma_pago', sa.TEXT(), nullable=True),
    sa.Column('numero_comprobante', sa.VARCHAR(length=100), nullable=True),
    sa.Column('precio_paquete', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
