"""empty message

Revision ID: 4b937539518b
Revises: 4031e8fdbc91
Create Date: 2025-08-08 10:08:51.370180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b937539518b'
down_revision = '4031e8fdbc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abono_caminata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_cancela', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abono_caminata', schema=None) as batch_op:
        batch_op.drop_column('periodo_cancela')

    # ### end Alembic commands ###
