"""Datos para asegurado

Revision ID: 8d16008a9e0f
Revises: 2a4e8a4c4926
Create Date: 2025-08-06 13:13:01.748816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d16008a9e0f'
down_revision = '2a4e8a4c4926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poliza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('precio_poliza', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monto_cancelacion', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cuenta_deposito', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sinpe_deposito', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poliza', schema=None) as batch_op:
        batch_op.drop_column('sinpe_deposito')
        batch_op.drop_column('cuenta_deposito')
        batch_op.drop_column('banco')
        batch_op.drop_column('monto_cancelacion')
        batch_op.drop_column('precio_poliza')
        batch_op.drop_column('fecha_vencimiento')

    # ### end Alembic commands ###
