"""Add new columns to models

Revision ID: 97137945f07c
Revises: fc0a83d7065c
Create Date: 2025-08-12 22:50:23.167697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97137945f07c'
down_revision = 'fc0a83d7065c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aerolinea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono_prealertar', sa.String(length=20), nullable=True))

    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_individual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reserva', sa.String(length=50), nullable=True))
        batch_op.drop_column('fecha_disponible')
        batch_op.drop_column('alimentacion_incluida')
        batch_op.drop_column('cpl')

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_individual', sa.Float(), nullable=True))

    with op.batch_alter_table('lugar_visitar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_c_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cant_s_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_individual', sa.Float(), nullable=True))

    with op.batch_alter_table('otro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_individual', sa.Float(), nullable=True))

    with op.batch_alter_table('transporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_c_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cant_s_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_cambio_transporte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('colones', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_tc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_individual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transporte', schema=None) as batch_op:
        batch_op.drop_column('total_individual')
        batch_op.drop_column('total_tc')
        batch_op.drop_column('colones')
        batch_op.drop_column('tipo_cambio_transporte')
        batch_op.drop_column('cant_s_guias')
        batch_op.drop_column('cant_c_guias')

    with op.batch_alter_table('otro', schema=None) as batch_op:
        batch_op.drop_column('total_individual')

    with op.batch_alter_table('lugar_visitar', schema=None) as batch_op:
        batch_op.drop_column('total_individual')
        batch_op.drop_column('cant_s_guias')
        batch_op.drop_column('cant_c_guias')

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.drop_column('total_individual')

    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpl', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('alimentacion_incluida', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('fecha_disponible', sa.DATE(), nullable=True))
        batch_op.drop_column('reserva')
        batch_op.drop_column('total_individual')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('aerolinea', schema=None) as batch_op:
        batch_op.drop_column('telefono_prealertar')

    # ### end Alembic commands ###
