"""Migración inicial del sistema de rifas

Revision ID: f13e807a04f3
Revises: 
Create Date: 2025-09-09 10:17:01.311717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13e807a04f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_column('fecha_caminata')
        batch_op.drop_column('hora_inicio_caminata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio_caminata', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_caminata', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
