"""empty message

Revision ID: fc0a83d7065c
Revises: fd1e8b7268c9
Create Date: 2025-08-12 21:20:33.208707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0a83d7065c'
down_revision = 'fd1e8b7268c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_c_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cant_s_guias', sa.Integer(), nullable=True))

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cant_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cant_s_guias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cant_acarreo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.drop_column('cant_acarreo')
        batch_op.drop_column('cant_s_guias')
        batch_op.drop_column('cant_guias')

    with op.batch_alter_table('estadia', schema=None) as batch_op:
        batch_op.drop_column('cant_s_guias')
        batch_op.drop_column('cant_c_guias')

    # ### end Alembic commands ###
