"""empty message

Revision ID: fd1e8b7268c9
Revises: 
Create Date: 2025-08-10 23:24:05.109447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1e8b7268c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificultad', sa.String(length=50), nullable=False, server_default='Básico'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruta', schema=None) as batch_op:
        batch_op.drop_column('dificultad')

    # ### end Alembic commands ###
